name: test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['20.3', '22.3']
        elixir: ['1.6.5', '1.8.2', '1.9.4', '1.10.4']
        exclude:
          - elixir: '1.10.4'
            otp: '20.3'
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: erlef/setup-beam@v1.7.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get --only test
      - run: mix test
